no.nav:
  security:
     jwt:
       issuer:
         selvbetjening:
           discoveryurl: ${loginservice.idporten.discovery.url}
           accepted_audience: ${loginservice.idporten.audience}

http:
  proxy : http://webproxy-nais.nav.no:8088

management:
    endpoint:
      health:    
       show-details : never
    metrics:
      web:
        server:
          request:
            autotime:
              enabled: true
    endpoints:
      web:
        exposure:
          include:  info, health, metrics, prometheus
    health :
      diskspace:
        enabled: false
      jms:
        enabled: false
server:
    servlet:
      context-path: /api
    forward-headers-strategy: framework
spring:
    cloud:
      discovery:
        client:
          health-indicator:
            enabled: false
    cache :
      cache-names : aktør, fnr, organisasjon, navn
      caffeine.spec: maximumSize=100,expireAfterAccess=3600s
    application:
      name : fpsoknad-oppslag
    jackson:
      default-property-inclusion: non-null
      deserialization:
         accept-single-value-as-array: true
         fail-on-unknown-properties: false
      serialization:
         fail-on-empty-beans: false
    main.banner-mode: 'off'
    
virksomhet:
  arbeidsforhold:
    v3:
      endpointurl: https://modapp.adeo.no/aareg-services/ArbeidsforholdService/v3
  organisasjon:
    v5: 
      endpointurl: https://modapp.adeo.no/ereg/ws/OrganisasjonService/v5
  person:
    v3:
      endpointurl: https://wasapp.adeo.no/tpsws/ws/Person/v3
aktoer:
  v2:
    endpointurl: https://app.adeo.no/aktoerregister/ws/Aktoer/v2 
    
securitytokenservice:
    username: ${fpselvbetjening.username}
    password : ${fpselvbetjening.password}
    url: https://sts.adeo.no/SecurityTokenServiceProvider/          
