no.nav:
     security.jwt.issuer.selvbetjening:
        discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
        cookie_name: selvbetjening-idtoken

info.app:
    version: '@project.version@'
    build.time:  '@timestamp@'

http:
  proxy : http://webproxy-nais.nav.no:8088

management:
    endpoint:
      health:    
       show-details : never
    metrics:
      web:
        server:
          request:
            autotime:
              enabled: true
    endpoints:
      web:
        exposure:
          include:  info, health, metrics, prometheus
    health :
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true
      diskspace:
        enabled: false
      jms:
        enabled: false
server:
    servlet:
      context-path: /api
    forward-headers-strategy: framework
spring:
    cloud.discovery.client.health-indicator.enabled: false
    cache :
      cache-names : aktør, fnr, organisasjon, navn
      caffeine.spec: maximumSize=100,expireAfterAccess=3600s
    application:
      name : fpsoknad-oppslag
    jackson:
      default-property-inclusion: non-null
      deserialization:
         accept-single-value-as-array: true
         fail-on-unknown-properties: false
      serialization:
         fail-on-empty-beans: false
    main.banner-mode: 'off'
