no.nav.security.jwt.issuer.selvbetjening.discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
sts.uri: https://security-token-service.nais.preprod.local/rest/v1/sts/token?grant_type=client_credentials&scope=openid
management :
   endpoints:
     web:
       exposure:
         include:  '*'
   endpoint:
     health:
       show-details : always
     security:
       enabled : false

spring:
  mvc:
    log-request-details : true
org:
  apache:
    cxf:
      logging:
        enable : true
             
virksomhet:
  arbeidsforhold:
    v3:
      endpointurl: https://modapp-q1.adeo.no/aareg-services/ArbeidsforholdService/v3
  organisasjon:
    v5: 
      endpointurl: https://modapp-q1.adeo.no/ereg/ws/OrganisasjonService/v5
  person:
    v3:
      endpointurl: https://wasapp-q1.adeo.no/tpsws/ws/Person/v3
aktoer:
  v2:
    endpointurl: https://app-q1.adeo.no/aktoerregister/ws/Aktoer/v2
    
securitytokenservice:
    url: https://sts-q1.preprod.local/SecurityTokenServiceProvider/