management :
   endpoints.web.exposure.include:  '*'
   endpoint:
     health.show-details : always
     security.enabled : false

no.nav.security.oidc:
  issuers: selvbetjening
  issuer:
    selvbetjening.discoveryurl: http://metadata
    selvbetjening.accepted_audience: aud-localhost
    selvbetjening.cookie_name: localhost-idtoken

securitytokenservice.uri:  http://localhost
http.proxy:

AKTOER_V2_ENDPOINTURL: http://localhost
JOURNAL_V2_ENDPOINTURL: http://localhost
VIRKSOMHET_ARBEIDSFORHOLD_V3_ENDPOINTURL: http://localhost
VIRKSOMHET_INNTEKT_V3_ENDPOINTURL:  http://localhost
VIRKSOMHET_PERSON_V3_ENDPOINTURL:  http://localhost
VIRKSOMHET_YTELSESKONTRAKT_V3_ENDPOINTURL: http://localhost
VIRKSOMHET_FORELDREPENGESAK_V1_ENDPOINTURL: http://localhost
VIRKSOMHET_SAK_V2_ENDPOINTURL: http://localhost
VIRKSOMHET_INFOTRYGDSAK_V1_ENDPOINTURL: http://localhost
VIRKSOMHET_MEDLEMSKAP_V2_ENDPOINTURL: http://localhost
VIRKSOMHET_ORGANISASJON_V5_ENDPOINTURL: http://localhost
SAK_SAKER_URL: http://localhost
SECURITYTOKENSERVICE_URL: http://localhost
FPSELVBETJENING_USERNAME: something
FPSELVBETJENING_PASSWORD: bogus

server.port: 9000
