name: Deployment pipeline q1

on:
  push:
env:
  CLUSTER: dev-fss
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpsoknad-oppslag
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - name: Lukk deployment-issues
        uses: actions/github-script@0.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['bygg']
            }).then(response => {
              response.data.forEach(issue => {
                github.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              });
            });
    
      - name: Sjekk ut kode
        uses: actions/checkout@v1
     
      - name: Hent tag    
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)"  
             
      - name: Hent Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
  
      - name: Sett opp Java 8      
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Kompiler
        run: | 
          echo "::set-env name=IMAGE::$IMAGE_BASE:$TAG" 
          mvn clean install --batch-mode --quiet 
                   
      - name: Bygg, tag og push Docker image  
        run: |
          docker build --tag ${IMAGE} --tag ${IMAGE_BASE}:latest .
          echo  ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE_BASE}   
    
      - name: Opprett deployment issue
        if: success()
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: createdeployissue
        with:
          labels : 'bygg' 
          token: ${{ secrets.NOTIFICATION }}
          title: Deploy av ${{ env.TAG }}
          body: |
            Kommenter med <b>/promote cluster</b>, hvor <b>cluster</b> er et gyldig clusternavn
            <table>
            <tr><th>Cluster</th></tr>
            <tr><td>dev-fss</td></tr>
            <tr><td>prod-fss</td></tr>
            </table>
      
      - name: Trigg deploy til dev-fss
        if: success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          issue-number: ${{ steps.createdeployissue.outputs.number }}
          body: /promote  ${{ env.CLUSTER }}
